#Break time in ticks
#0 = instabreak
#List of material name : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
breaktime:
  WOOD: 20
  COBWEB: 20
#Only check those data values
#If no data value is selected for a material that is in the list at the top, all data values will be checked
#Data as LIST, even if there is only one element. Format is :
#datavalues:
#  MATERIAL: [0, 1, 3, 6]
#  MATERIAL2: [4]
datavalues:
  COBWEB: [1]

#The plugin will only work for people having this permission. You can change it.
#If you don't want to use permissions for usage, set it to "none".
#Setting the reload permission to "none" won't work.
permissions:
  reload: "fastbreak.reload"
  use: "fastbreak.use"
