name: FastBreak
version: 1.13.2-R0.1
api-version: 1.13
main: ch.geeq.Cut
author: Weby
depend: [ProtocolLib]
commands:
  fastbreakreload:
    usage: Reloads the custom configuration
    permission: fastbreak.reload