name: FastBreak
version: 1.0.0
main: ch.geeq.Cut
author: Weby
depend: [ProtocolLib]
commands:
  wcsm:
    usage: No usage / legacy command
    permission: fastbreak.reload
  wcre:
    usage: Reloads the custom configuration
    permission: fastbreak.reload
  fastbreakreload:
    usage: Reloads the custom configuration
    permission: fastbreak.reload